modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="logisticpipes"
version="0.2.0.1"
displayName="Pipecraft"
authors="leplopp"
description='''Logistical Pipes adds Pipes & viaducts with many Features and options'''

[[mixins]]
config="pipecraft.mixins.json"

[[dependencies.pipecraft]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.pipecraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"