modLoader="javafml"
loaderVersion="*"
license="MIT"

[[mods]]
modId="logisticpipes"
version="0.3.1.1"
displayName="PipeCraft"
logoFile="logo.png"
authors="leplopp"
description='''Adds player transport pipes (Viaducts) inspired by the old Thermal mods.'''
issueTrackerURL="https://github.com/leplopp/Logistical-Pipes/issues"
displayURL="https://modrinth.com/mod/pipecraft"

[[mixins]]
config="pipecraft.mixins.json"

[modproperties.logisticpipes]

[[dependencies.logisticpipes]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"