modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="logisticpipes"
version="0.3.0"
displayName="PipeCraft"
logoFile="logo.png"
authors="leplopp"
description='''Adds player transport pipes (Viaducts) inspired by the old Thermal mods.'''
issueTrackerURL="https://github.com/leplopp/Logistical-Pipes/issues"
displayURL="https://modrinth.com/mod/pipecraft"

[[mixins]]
config="pipecraft.mixins.json"

[[dependencies.pipecraft]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.pipecraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"